# Codecov Configuration for gRPCServer.jl
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "docs/**/*"
  - "test/**/*"
  - "examples/**/*"
  - "specs/**/*"
