# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T15:15:53.337
# original file: /home/scelles-admin/.julia/dev/gRPCServer/specs/001-grpc-server/contracts/health.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export HealthCheckRequest, var"HealthCheckResponse.ServingStatus", HealthCheckResponse


struct HealthCheckRequest
    service::String
end
PB.default_values(::Type{HealthCheckRequest}) = (;service = "")
PB.field_numbers(::Type{HealthCheckRequest}) = (;service = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:HealthCheckRequest})
    service = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            service = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return HealthCheckRequest(service)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::HealthCheckRequest)
    initpos = position(e.io)
    !isempty(x.service) && PB.encode(e, 1, x.service)
    return position(e.io) - initpos
end
function PB._encoded_size(x::HealthCheckRequest)
    encoded_size = 0
    !isempty(x.service) && (encoded_size += PB._encoded_size(x.service, 1))
    return encoded_size
end

@enumx var"HealthCheckResponse.ServingStatus" UNKNOWN=0 SERVING=1 NOT_SERVING=2 SERVICE_UNKNOWN=3

struct HealthCheckResponse
    status::var"HealthCheckResponse.ServingStatus".T
end
PB.default_values(::Type{HealthCheckResponse}) = (;status = var"HealthCheckResponse.ServingStatus".UNKNOWN)
PB.field_numbers(::Type{HealthCheckResponse}) = (;status = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:HealthCheckResponse})
    status = var"HealthCheckResponse.ServingStatus".UNKNOWN
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            status = PB.decode(d, var"HealthCheckResponse.ServingStatus".T)
        else
            Base.skip(d, wire_type)
        end
    end
    return HealthCheckResponse(status)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::HealthCheckResponse)
    initpos = position(e.io)
    x.status != var"HealthCheckResponse.ServingStatus".UNKNOWN && PB.encode(e, 1, x.status)
    return position(e.io) - initpos
end
function PB._encoded_size(x::HealthCheckResponse)
    encoded_size = 0
    x.status != var"HealthCheckResponse.ServingStatus".UNKNOWN && (encoded_size += PB._encoded_size(x.status, 1))
    return encoded_size
end

# TODO: SERVICE
#    Health
