#
# Proto Descriptors Module
#
# This module loads pre-compiled protobuf file descriptors (.pb files) as
# constants for use by the gRPC reflection service.
#
# The .pb files are generated by protoc from the .proto source files.
# To regenerate them, run: julia src/proto/descriptors/generate.jl
#

"""
    extract_file_descriptors(descriptor_set::Vector{UInt8}) -> Vector{Vector{UInt8}}

Extract individual FileDescriptorProto messages from a FileDescriptorSet.

The FileDescriptorSet format is:
- Field 1 (tag 0x0A, length-delimited): repeated FileDescriptorProto

This function parses the FileDescriptorSet and returns the raw bytes of each
FileDescriptorProto, which is what the gRPC reflection API expects.
"""
function extract_file_descriptors(descriptor_set::Vector{UInt8})::Vector{Vector{UInt8}}
    result = Vector{Vector{UInt8}}()
    pos = 1
    len = length(descriptor_set)

    while pos <= len
        # Read tag (should be 0x0A for field 1, wire type 2 = length-delimited)
        if descriptor_set[pos] != 0x0A
            @warn "Unexpected tag in FileDescriptorSet" tag=descriptor_set[pos] pos=pos
            break
        end
        pos += 1

        # Read varint length
        field_len = 0
        shift = 0
        while pos <= len
            byte = descriptor_set[pos]
            pos += 1
            field_len |= (Int(byte & 0x7F) << shift)
            if (byte & 0x80) == 0
                break
            end
            shift += 7
        end

        # Extract the FileDescriptorProto bytes
        if pos + field_len - 1 <= len
            push!(result, descriptor_set[pos:pos+field_len-1])
            pos += field_len
        else
            @warn "FileDescriptorSet truncated" expected_len=field_len available=len-pos+1
            break
        end
    end

    return result
end

"""
    DESCRIPTOR_DIR

Directory containing the compiled .pb descriptor files.
"""
const DESCRIPTOR_DIR = joinpath(@__DIR__, "descriptors")

"""
    _load_descriptor(filename::String) -> Vector{UInt8}

Load a .pb descriptor file and return its raw bytes.
Returns an empty vector if the file doesn't exist.
"""
function _load_descriptor(filename::String)
    filepath = joinpath(DESCRIPTOR_DIR, filename)
    if isfile(filepath)
        return read(filepath)
    else
        @warn "Descriptor file not found: $filepath. Run: julia src/proto/descriptors/generate.jl"
        return UInt8[]
    end
end

# Raw FileDescriptorSet bytes (for reference)
const _HEALTH_DESCRIPTOR_SET = _load_descriptor("health.pb")
const _REFLECTION_DESCRIPTOR_SET = _load_descriptor("reflection.pb")

"""
    HEALTH_DESCRIPTOR::Vector{Vector{UInt8}}

Extracted FileDescriptorProto messages for the gRPC Health service (grpc.health.v1).
Each element is a serialized FileDescriptorProto that can be returned by the reflection service.

Generated from: specs/001-grpc-server/contracts/health.proto
"""
const HEALTH_DESCRIPTOR = extract_file_descriptors(_HEALTH_DESCRIPTOR_SET)

"""
    REFLECTION_DESCRIPTOR::Vector{Vector{UInt8}}

Extracted FileDescriptorProto messages for the gRPC Server Reflection service (grpc.reflection.v1alpha).
Each element is a serialized FileDescriptorProto that can be returned by the reflection service.

Generated from: specs/001-grpc-server/contracts/reflection.proto
"""
const REFLECTION_DESCRIPTOR = extract_file_descriptors(_REFLECTION_DESCRIPTOR_SET)

"""
    has_health_descriptor() -> Bool

Check if the Health service descriptor is available.
"""
has_health_descriptor() = !isempty(HEALTH_DESCRIPTOR)

"""
    has_reflection_descriptor() -> Bool

Check if the Reflection service descriptor is available.
"""
has_reflection_descriptor() = !isempty(REFLECTION_DESCRIPTOR)
