# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-01-10T15:15:58.445
# original file: /home/scelles-admin/.julia/dev/gRPCServer/specs/001-grpc-server/contracts/reflection.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export ServiceResponse, FileDescriptorResponse, ErrorResponse, ExtensionRequest
export ExtensionNumberResponse, ListServiceResponse, ServerReflectionRequest
export ServerReflectionResponse


struct ServiceResponse
    name::String
end
PB.default_values(::Type{ServiceResponse}) = (;name = "")
PB.field_numbers(::Type{ServiceResponse}) = (;name = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ServiceResponse})
    name = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            name = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ServiceResponse(name)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ServiceResponse)
    initpos = position(e.io)
    !isempty(x.name) && PB.encode(e, 1, x.name)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ServiceResponse)
    encoded_size = 0
    !isempty(x.name) && (encoded_size += PB._encoded_size(x.name, 1))
    return encoded_size
end

struct FileDescriptorResponse
    file_descriptor_proto::Vector{Vector{UInt8}}
end
PB.default_values(::Type{FileDescriptorResponse}) = (;file_descriptor_proto = Vector{Vector{UInt8}}())
PB.field_numbers(::Type{FileDescriptorResponse}) = (;file_descriptor_proto = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FileDescriptorResponse})
    file_descriptor_proto = PB.BufferedVector{Vector{UInt8}}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, file_descriptor_proto)
        else
            Base.skip(d, wire_type)
        end
    end
    return FileDescriptorResponse(file_descriptor_proto[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FileDescriptorResponse)
    initpos = position(e.io)
    !isempty(x.file_descriptor_proto) && PB.encode(e, 1, x.file_descriptor_proto)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FileDescriptorResponse)
    encoded_size = 0
    !isempty(x.file_descriptor_proto) && (encoded_size += PB._encoded_size(x.file_descriptor_proto, 1))
    return encoded_size
end

struct ErrorResponse
    error_code::Int32
    error_message::String
end
PB.default_values(::Type{ErrorResponse}) = (;error_code = zero(Int32), error_message = "")
PB.field_numbers(::Type{ErrorResponse}) = (;error_code = 1, error_message = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ErrorResponse})
    error_code = zero(Int32)
    error_message = ""
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            error_code = PB.decode(d, Int32)
        elseif field_number == 2
            error_message = PB.decode(d, String)
        else
            Base.skip(d, wire_type)
        end
    end
    return ErrorResponse(error_code, error_message)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ErrorResponse)
    initpos = position(e.io)
    x.error_code != zero(Int32) && PB.encode(e, 1, x.error_code)
    !isempty(x.error_message) && PB.encode(e, 2, x.error_message)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ErrorResponse)
    encoded_size = 0
    x.error_code != zero(Int32) && (encoded_size += PB._encoded_size(x.error_code, 1))
    !isempty(x.error_message) && (encoded_size += PB._encoded_size(x.error_message, 2))
    return encoded_size
end

struct ExtensionRequest
    containing_type::String
    extension_number::Int32
end
PB.default_values(::Type{ExtensionRequest}) = (;containing_type = "", extension_number = zero(Int32))
PB.field_numbers(::Type{ExtensionRequest}) = (;containing_type = 1, extension_number = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExtensionRequest})
    containing_type = ""
    extension_number = zero(Int32)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            containing_type = PB.decode(d, String)
        elseif field_number == 2
            extension_number = PB.decode(d, Int32)
        else
            Base.skip(d, wire_type)
        end
    end
    return ExtensionRequest(containing_type, extension_number)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExtensionRequest)
    initpos = position(e.io)
    !isempty(x.containing_type) && PB.encode(e, 1, x.containing_type)
    x.extension_number != zero(Int32) && PB.encode(e, 2, x.extension_number)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExtensionRequest)
    encoded_size = 0
    !isempty(x.containing_type) && (encoded_size += PB._encoded_size(x.containing_type, 1))
    x.extension_number != zero(Int32) && (encoded_size += PB._encoded_size(x.extension_number, 2))
    return encoded_size
end

struct ExtensionNumberResponse
    base_type_name::String
    extension_number::Vector{Int32}
end
PB.default_values(::Type{ExtensionNumberResponse}) = (;base_type_name = "", extension_number = Vector{Int32}())
PB.field_numbers(::Type{ExtensionNumberResponse}) = (;base_type_name = 1, extension_number = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ExtensionNumberResponse})
    base_type_name = ""
    extension_number = PB.BufferedVector{Int32}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            base_type_name = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, wire_type, extension_number)
        else
            Base.skip(d, wire_type)
        end
    end
    return ExtensionNumberResponse(base_type_name, extension_number[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ExtensionNumberResponse)
    initpos = position(e.io)
    !isempty(x.base_type_name) && PB.encode(e, 1, x.base_type_name)
    !isempty(x.extension_number) && PB.encode(e, 2, x.extension_number)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ExtensionNumberResponse)
    encoded_size = 0
    !isempty(x.base_type_name) && (encoded_size += PB._encoded_size(x.base_type_name, 1))
    !isempty(x.extension_number) && (encoded_size += PB._encoded_size(x.extension_number, 2))
    return encoded_size
end

struct ListServiceResponse
    service::Vector{ServiceResponse}
end
PB.default_values(::Type{ListServiceResponse}) = (;service = Vector{ServiceResponse}())
PB.field_numbers(::Type{ListServiceResponse}) = (;service = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ListServiceResponse})
    service = PB.BufferedVector{ServiceResponse}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, service)
        else
            Base.skip(d, wire_type)
        end
    end
    return ListServiceResponse(service[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ListServiceResponse)
    initpos = position(e.io)
    !isempty(x.service) && PB.encode(e, 1, x.service)
    return position(e.io) - initpos
end
function PB._encoded_size(x::ListServiceResponse)
    encoded_size = 0
    !isempty(x.service) && (encoded_size += PB._encoded_size(x.service, 1))
    return encoded_size
end

struct ServerReflectionRequest
    host::String
    message_request::Union{Nothing,OneOf{<:Union{String,ExtensionRequest}}}
end
PB.oneof_field_types(::Type{ServerReflectionRequest}) = (;
    message_request = (;file_by_filename=String, file_containing_symbol=String, file_containing_extension=ExtensionRequest, all_extension_numbers_of_type=String, list_services=String),
)
PB.default_values(::Type{ServerReflectionRequest}) = (;host = "", file_by_filename = "", file_containing_symbol = "", file_containing_extension = nothing, all_extension_numbers_of_type = "", list_services = "")
PB.field_numbers(::Type{ServerReflectionRequest}) = (;host = 1, file_by_filename = 3, file_containing_symbol = 4, file_containing_extension = 5, all_extension_numbers_of_type = 6, list_services = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ServerReflectionRequest})
    host = ""
    message_request = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            host = PB.decode(d, String)
        elseif field_number == 3
            message_request = OneOf(:file_by_filename, PB.decode(d, String))
        elseif field_number == 4
            message_request = OneOf(:file_containing_symbol, PB.decode(d, String))
        elseif field_number == 5
            message_request = OneOf(:file_containing_extension, PB.decode(d, Ref{ExtensionRequest}))
        elseif field_number == 6
            message_request = OneOf(:all_extension_numbers_of_type, PB.decode(d, String))
        elseif field_number == 7
            message_request = OneOf(:list_services, PB.decode(d, String))
        else
            Base.skip(d, wire_type)
        end
    end
    return ServerReflectionRequest(host, message_request)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ServerReflectionRequest)
    initpos = position(e.io)
    !isempty(x.host) && PB.encode(e, 1, x.host)
    if isnothing(x.message_request);
    elseif x.message_request.name === :file_by_filename
        PB.encode(e, 3, x.message_request[]::String)
    elseif x.message_request.name === :file_containing_symbol
        PB.encode(e, 4, x.message_request[]::String)
    elseif x.message_request.name === :file_containing_extension
        PB.encode(e, 5, x.message_request[]::ExtensionRequest)
    elseif x.message_request.name === :all_extension_numbers_of_type
        PB.encode(e, 6, x.message_request[]::String)
    elseif x.message_request.name === :list_services
        PB.encode(e, 7, x.message_request[]::String)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::ServerReflectionRequest)
    encoded_size = 0
    !isempty(x.host) && (encoded_size += PB._encoded_size(x.host, 1))
    if isnothing(x.message_request);
    elseif x.message_request.name === :file_by_filename
        encoded_size += PB._encoded_size(x.message_request[]::String, 3)
    elseif x.message_request.name === :file_containing_symbol
        encoded_size += PB._encoded_size(x.message_request[]::String, 4)
    elseif x.message_request.name === :file_containing_extension
        encoded_size += PB._encoded_size(x.message_request[]::ExtensionRequest, 5)
    elseif x.message_request.name === :all_extension_numbers_of_type
        encoded_size += PB._encoded_size(x.message_request[]::String, 6)
    elseif x.message_request.name === :list_services
        encoded_size += PB._encoded_size(x.message_request[]::String, 7)
    end
    return encoded_size
end

struct ServerReflectionResponse
    valid_host::String
    original_request::Union{Nothing,ServerReflectionRequest}
    message_response::Union{Nothing,OneOf{<:Union{FileDescriptorResponse,ExtensionNumberResponse,ListServiceResponse,ErrorResponse}}}
end
PB.oneof_field_types(::Type{ServerReflectionResponse}) = (;
    message_response = (;file_descriptor_response=FileDescriptorResponse, all_extension_numbers_response=ExtensionNumberResponse, list_services_response=ListServiceResponse, error_response=ErrorResponse),
)
PB.default_values(::Type{ServerReflectionResponse}) = (;valid_host = "", original_request = nothing, file_descriptor_response = nothing, all_extension_numbers_response = nothing, list_services_response = nothing, error_response = nothing)
PB.field_numbers(::Type{ServerReflectionResponse}) = (;valid_host = 1, original_request = 2, file_descriptor_response = 4, all_extension_numbers_response = 5, list_services_response = 6, error_response = 7)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:ServerReflectionResponse})
    valid_host = ""
    original_request = Ref{Union{Nothing,ServerReflectionRequest}}(nothing)
    message_response = nothing
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            valid_host = PB.decode(d, String)
        elseif field_number == 2
            PB.decode!(d, original_request)
        elseif field_number == 4
            message_response = OneOf(:file_descriptor_response, PB.decode(d, Ref{FileDescriptorResponse}))
        elseif field_number == 5
            message_response = OneOf(:all_extension_numbers_response, PB.decode(d, Ref{ExtensionNumberResponse}))
        elseif field_number == 6
            message_response = OneOf(:list_services_response, PB.decode(d, Ref{ListServiceResponse}))
        elseif field_number == 7
            message_response = OneOf(:error_response, PB.decode(d, Ref{ErrorResponse}))
        else
            Base.skip(d, wire_type)
        end
    end
    return ServerReflectionResponse(valid_host, original_request[], message_response)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::ServerReflectionResponse)
    initpos = position(e.io)
    !isempty(x.valid_host) && PB.encode(e, 1, x.valid_host)
    !isnothing(x.original_request) && PB.encode(e, 2, x.original_request)
    if isnothing(x.message_response);
    elseif x.message_response.name === :file_descriptor_response
        PB.encode(e, 4, x.message_response[]::FileDescriptorResponse)
    elseif x.message_response.name === :all_extension_numbers_response
        PB.encode(e, 5, x.message_response[]::ExtensionNumberResponse)
    elseif x.message_response.name === :list_services_response
        PB.encode(e, 6, x.message_response[]::ListServiceResponse)
    elseif x.message_response.name === :error_response
        PB.encode(e, 7, x.message_response[]::ErrorResponse)
    end
    return position(e.io) - initpos
end
function PB._encoded_size(x::ServerReflectionResponse)
    encoded_size = 0
    !isempty(x.valid_host) && (encoded_size += PB._encoded_size(x.valid_host, 1))
    !isnothing(x.original_request) && (encoded_size += PB._encoded_size(x.original_request, 2))
    if isnothing(x.message_response);
    elseif x.message_response.name === :file_descriptor_response
        encoded_size += PB._encoded_size(x.message_response[]::FileDescriptorResponse, 4)
    elseif x.message_response.name === :all_extension_numbers_response
        encoded_size += PB._encoded_size(x.message_response[]::ExtensionNumberResponse, 5)
    elseif x.message_response.name === :list_services_response
        encoded_size += PB._encoded_size(x.message_response[]::ListServiceResponse, 6)
    elseif x.message_response.name === :error_response
        encoded_size += PB._encoded_size(x.message_response[]::ErrorResponse, 7)
    end
    return encoded_size
end

# TODO: SERVICE
#    ServerReflection
